config/routes.rb
OlympicsQuiz::Application.routes.draw do

  get "questions/show"
  get "questions/results", as: 'results'
  root :to => 'static_pages#index'

  post '/users' => 'users#create', as: 'create_user'

  patch 'scores' => 'scores#update', as: 'update_score'

  get '/questions/:id' => 'questions#show', as: 'question'

end

app/models/answer.rb
class Answer < ActiveRecord::Base

  validates :values, presence: true, on: :update

end

app/models/question.rb
class Question < ActiveRecord::Base



end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
end

app/models/score.rb
class Score < ActiveRecord::Base

  validates :score, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def show

    if params[:question_id] == 1
      @q = Question.find_by(:id => params[:question_id])
    else
      @q = Question.find_by(:id => params[:id])
    end

    @a = Answer.where(:question_id => @q.index)

    @u = User.find_by(:id => session[:u_id])



    index_of_previous_question = @q.id-1
    previous_question = Question.find_by(:id => index_of_previous_question)



  end

  def result
    @user = User.all
    @score = Score.find_by(:user_id => @u.id)
  end

end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController

  def update

    @u = User.find_by(:id => session[:u_id])

    s = Score.find_by(:user_id => @u.id)



    if params[:answer_code] == '4'
    s.score += params[:answer_code].to_i
    end

    s.save

    if params[:page_index] == '11'
    	redirect_to results_url

    else

        if params[:answer_code] == '4'
    	redirect_to question_url(params[:page_index], :correct => true)
        else
        redirect_to question_url(params[:page_index], :correct => false)
        end

    end

  end


end







# Some old stuff

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController


  def index

    reset_session

  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def create


  u = User.new
  u.name = params[:Name]
  u.save

  s = Score.new
  s.user_id = u.id
  s.score = 0
  s.save

  session[:u_id] = u.id


  quiz = Quiz.new
  quiz.user_id = u.id
  quiz.save

  redirect_to question_url(1, :question_id => 1 )

end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Olympics Quiz</title>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
   <link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:400,300,200,700' rel='stylesheet' type='text/css'>

	<link rel="shortcut icon" href="/assets/favicon.ico" type="image/x-icon">
	<link rel="icon" href="/assets/favicon.ico" type="image/x-icon">
</head>
<body>

  <div class="body_content">

<%= yield %>

  </div>

<!-- <footer>

	<p>Olympic Quiz 2014</p>

</footer> -->

</body>
</html>

app/views/questions/results.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset=utf-8 />
<title>Olympics Quiz</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="/css/screen.css" media="all">
   <link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:400,300,200,700' rel='stylesheet' type='text/css'>
	<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
</head>

<body>

	<% @user = User.last %>
	<% @user_score_sheet = Score.find_by(:user_id => @user.id) %>
	<% @score_times_four = @user_score_sheet.score %>
	<% @score_out_of_ten = @score_times_four/4 %>

<div class="base">
    <div class="medal">
        <!-- Is THIS your card? -->

    <% if @score_out_of_ten == 10 %>
		<div class="gold_front"><p>1</p><img src="/assets/olympic_rings_white.png" alt="" width='100'></div>
        <div class="gold_back"><p>1</p><img src="/assets/olympic_rings_white.png" alt="" width='100'></div>
	<% end %>

	<% if @score_out_of_ten <= 5 %>
		<div class="no_medal_front"><p>SHAME</p><img src="/assets/olympic_rings_white.png" alt="" width='100'></div>
        <div class="no_medal_back"><p>SHAME</p><img src="/assets/olympic_rings_white.png" alt="" width='100'></div>
	<% end %>

	<% if @score_out_of_ten == 8 %>
		<div class="silver_front"><p>2</p><img src="/assets/olympic_rings_white.png" alt="" width='100'></div>
        <div class="silver_back"><p>2</p><img src="/assets/olympic_rings_white.png" alt="" width='100'></div>
	<% end %>

	<% if @score_out_of_ten == 9 %>
		<div class="silver_front"><p>2</p><img src="/assets/olympic_rings_white.png" alt="" width='100'></div>
        <div class="silver_back"><p>2</p><img src="/assets/olympic_rings_white.png" alt="" width='100'></div>
	<% end %>

	<% if @score_out_of_ten == 6 %>
		<div class="bronze_front"><p>3</p><img src="/assets/olympic_rings_white.png" alt="" width='100'></div>
        <div class="bronze_back"><p>3</p><img src="/assets/olympic_rings_white.png" alt="" width='100'></div>
	<% end %>

	<% if @score_out_of_ten == 7 %>
		<div class="bronze_front"><p>3</p><img src="/assets/olympic_rings_white.png" alt="" width='100'></div>
        <div class="bronze_back"><p>3</p><img src="/assets/olympic_rings_white.png" alt="" width='100'></div>
	<% end %>

    </div>
 </div>

<div class="results">
	<!-- INSERT RUBY FOR GOLD -->


	<% if @score_out_of_ten == 10 %>
		<h2>You won the GOLD!</h2>
	<% end %>

	<% if @score_out_of_ten <= 5 %>
		<h2>You did not place!</h2>
	<% end %>

	<% if @score_out_of_ten == 8 %>
		<h2>You won SILVER!</h2>
	<% end %>

	<% if @score_out_of_ten == 9 %>
		<h2>You won SILVER!</h2>
	<% end %>

	<% if @score_out_of_ten == 6 %>
		<h2>You won BRONZE!</h2>
	<% end %>

	<% if @score_out_of_ten == 7 %>
		<h2>You won BRONZE!</h2>
	<% end %>

	<p>Official Score: <%= @score_out_of_ten %>/10</p> <br>
	

	<p class="twitter">	<a href="https://twitter.com/share?text=I correctly identified <%= @score_out_of_ten %> out of 10 Olympic locations. Test your Olympic knowledge before the games begin! https://olympicsquiz.herokuapp.com" class="twitter-share-button" data-url="https://olympicsquiz.herokuapp.com" data-lang="en" data-count="none"><i class="fa fa-twitter-square fa-lg"></a></i> </p>

</div>


</body>
</html>

app/views/questions/show.html.erb
  <header class="question_header">
    <%= image_tag("/assets/rings_blue.png", width: '15%') %>
    <!-- <h1>Olym<span class='pics'>pics</span> Quiz</h1> -->

  </header>

  <div class="question_picture">
    <ul class="first">

      <li><%= image_tag("/assets/#{@q.picture_a}", class: 'first_image') %></li>
      <li><%= image_tag("/assets/#{@q.picture_b}", class: 'second_image') %></li>
      <li><%= image_tag("/assets/#{@q.picture_c}", class: 'third_image') %></li>

    </ul>

  </div>

  <h2>Guess this Olympic location.</h2>


<!-- NEW VERSION -->

  <% next_page = @q.index + 1 %>

  <% user = User.find_by(:id => session[:u_id]) %>

  <%= form_tag update_score_url, class: 'question_form', method: 'patch' do %>

    <% @a.each do |answer| %>

      <%= label_tag do %>
      <%= radio_button_tag('answer_code', answer.values) %>
      <%= answer.content %> <br>

      <% end %>


      <%= hidden_field_tag 'page_index', next_page %>

      <%= hidden_field_tag 'user_id', user.id %>


    <% end %>


  <%= button_tag 'Submit answer', class: 'next_page' %>

  <% end %>


<% if params[:correct] == 'true' %>
<div class="question_right">
You're last answer was right.
</div>
<% elsif @q.index == 1%>

<% else %>
<div class="question_wrong">
You're last answer was wrong.
</div>
<% end %>



<% if @q.index < 10 %>
<div class="question_count">
<%= 10 - @q.index %> more questions to go.
</div>
<% else %>
<div class="question_count">
This is the last question.
</div>
<% end %>

app/views/static_pages/index.html.erb
  <div class="olympic_logo">
 <!--    <img src="assets/images/rings_blue.png" alt="Olympic Rings" width='55%'> -->

 <%= image_tag("/assets/rings_blue.png", width: '50%') %>

  </div>

  <header>
    <h1>Olym<span class='pics'>pics</span> Quiz</h1>
    <p>Test your knowledge of the Olympics through pictures.</p>
  </header>


  <%= form_tag create_user_url, class: 'homepage_form', method: 'post' do %>

    <%= label_tag '' %>
    <%= text_field_tag 'Name', nil, placeholder: 'Please enter your name to get started...' %>

    <%= hidden_field_tag 'question_id', "1" %>

    <br>
    <%= button_tag 'Click to start!' %>


  <% end %>